server:
  port: 8800

#数据源配置
spring:
  application:
    name: java-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkjimin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


#consumer
rocketmq:
  name-server: 192.168.0.104:9876
  consumer:
    consumer-thread-min: 20
    consumer-thread-max: 64
    #设置一次消费消息的条数，默认为1条
    consume-message-batch-max-size: 1
    topics:
      sync:
        name: sync
        consumerGroup: sync
      async:
        name: async
        consumerGroup: async
      orderly:
        name: orderly
        consumerGroup: orderly
      oneway:
        name: oneway
        consumerGroup: oneway
      delay:
        name: delay
        consumerGroup: delay
      batch:
        name: batch
        consumerGroup: batch
      filter:
        name: filter
        consumerGroup: filter
      transaction:
        name: transaction
        consumerGroup: transaction

