server:
  port: 8800

#数据源配置
spring:
  application:
    name: java-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkjimin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


#consumer
rocketmq:
  consumer:
    group-name: java-8
    #mq的nameserver地址
    namesev-addr: 192.168.0.104:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    consumer-thread-min: 20
    consumer-thread-max: 64
    #设置一次消费消息的条数，默认为1条
    consume-message-batch-max-size: 1
    topics:
      blog:
        name: blog
        consumerGroup: blog
      user:
        name: user
        consumerGroup: user


