server:
  port: 8800

#数据源配置
spring:
  application:
    name: java-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkjimin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    ##redis 单机环境配置
    host: 192.168.0.104
    port: 6379
    password:
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000

#mybatis-plus:

#rocketmq
#rocketmq:
#  accessKey: LTAIaC0QRYJ8qshF
#  secretKey: kwbBbjGlnG8eZupIDNu7M9fYYoX6pG
#  nameSrvAddr: http://MQ_INST_1405563119862290_BbQgln7s.mq-internet-access.mq-internet.aliyuncs.com:80
#  topic: demoTopic
#  groupId: GID-demo
#  tag: tag
#  orderTopic: none
#  orderGroupId: none
#  orderTag: orderTag

#producer
#rocketmq:
#  producer:
#    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
#    groupName: ${spring.application.name}
#    #mq的nameserver地址
#    namesrvAddr: 192.168.0.104:9876
#    #消息最大长度 默认1024*4(4M)
#    maxMessageSize: 4096
#    #发送消息超时时间,默认3000
#    sendMsgTimeout: 3000
#    #发送消息失败重试次数，默认2
#    retryTimesWhenSendFailed: 2

#consumer
#rocketmq:
#  consumer:
#    groupName: java-8
#    #mq的nameserver地址
#    namesevAddr: 192.168.0.104:9876
#    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
#    #topics: demoTopic~*;
#    topics: demoTopic
#    consumerThreadMin: 20
#    consumerThreadMax: 64
#    #设置一次消费消息的条数，默认为1条
#    consumeMessageBatchMaxSize: 1

